[tool.poetry]
name = "itemsubjectorapp"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "GPLv3+"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.5.3"
flask = "^3.0.1"
black = "^23.12.1"
wikibaseintegrator = "^0.12.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
